- package.json
- src/App.tsx
- src/pages/404/404.styles.ts
- src/pages/404/404.tsx
> Add 404 not found page

- src/App.styles.ts
- src/App.tsx
- src/components/Footer/Footer.styles.ts
- src/components/Footer/Footer.tsx
- src/components/Header/Header.tsx
Added
- `Footer` component
- `Header` and `Footer` alignment
- Footer logo and twitter icon
> Footer component

- src/App.tsx
- src/components/SearchBar/SearchBar.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/Table/Table.styles.ts
- src/components/Table/Table.tsx
- src/pages/Explorer/Explorer.tsx
- src/routes/Routes.tsx
- src/routes/index.tsx
- src/utils/axios/axios.ts
- src/utils/constants/urls.ts
Added
- `Table` component and styles
- `Explorer` last transactions section
- `LAST_TRANSACTIONS` url
- `Routes` `SearchBar` `SideBar` `App` `axios` clean ups
> Homepage Last Transactions

- src/pages/Network/Network.tsx
- src/utils/constants/urls.ts
- src/utils/types/IConnections.ts
Added
- `Network` table
- `Connections` url and interface
> Network Connection Table

- package.json
- src/components/Map/Map.options.ts
- src/components/Map/Map.styles.ts
- src/components/Map/Map.tsx
- src/components/Map/map.css
- src/pages/Explorer/Explorer.helpers.ts
- src/pages/Explorer/Explorer.tsx
- src/utils/types/react-jvectormap/index.d.ts
- yarn.lock
Added
- `Map` component
- `Map` styles and global styles
- `Map` mock options to render markers
- `react-jvectormap` module
Installed
- `react-jvectormap` library
> Map Component

- src/components/Charts/DoughnutChart/DoughnutChart.styles.ts
- src/components/Map/Map.options.ts
- src/components/Summary/Summary.tsx
- src/pages/Explorer/Explorer.helpers.tsx
- src/pages/Movement/Movement.tsx
- src/theme/variants.ts
Added
- `Theme` custom colors
- Color adjustments across application
> Theme colors

- src/components/Summary/Summary.tsx
- src/pages/Explorer/Explorer.helpers.tsx
- src/pages/Explorer/Explorer.tsx
- src/pages/Movement/Movement.helpers.ts
- src/pages/Movement/Movement.tsx
- src/utils/helpers/date/date.ts
- src/utils/helpers/formatNumbers/formatNumbers.ts
Changes:
- Add helper method to format numbers to currency
- Add helper to format dates to user local date based on timestamp
> Add helpers to format date and numbers

- src/pages/Details/BlockDetails/BlockDetails.helpers.ts
- src/pages/Details/BlockDetails/BlockDetails.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.helpers.ts
- src/pages/Details/TransactionDetails/TransactionDetails.tsx
- src/utils/constants/routes.ts
- src/utils/constants/urls.ts
- src/utils/types/IBlocks.ts
- src/utils/types/ITransactions.ts
Added
- `Transactions` API integration
- `Blocks` API integration
> Transactions and Block API integration

- src/pages/Blocks/Blocks.tsx
- src/pages/Details/BlockDetails/BlockDetails.helpers.ts
- src/pages/Details/BlockDetails/BlockDetails.tsx
- src/routes/index.tsx
- src/utils/constants/routes.ts
- src/utils/types/IBlocks.ts
- src/utils/types/ITransactions.ts
Added
- `Blocks` page and routes
- `Blocks details` with actual data
Updated
- `Iblock` and `ITransaction` interfaces
> Blocks list and details

- src/pages/Details/AddressDetails/AddressDetails.helpers.ts
- src/pages/Details/AddressDetails/AddressDetails.tsx
- src/pages/Explorer/Explorer.tsx
- src/pages/Movement/Movement.helpers.ts
- src/pages/Movement/Movement.styles.ts
- src/pages/Movement/Movement.tsx
- src/utils/helpers/formatNumbers/formatNumbers.ts
- src/utils/types/IAddress.ts
Added
- `Address` details and interface
Updated
- `Amount` typo
Removed
- `Movement` amount colors
> address details page updated with real data

- src/pages/Details/AddressDetails/AddressDetails.tsx
- src/pages/Details/BlockDetails/BlockDetails.helpers.ts
- src/pages/Details/BlockDetails/BlockDetails.tsx
- src/utils/constants/routes.ts
- src/utils/constants/urls.ts
- src/utils/types/IAddress.ts
- src/utils/types/IBlocks.ts
Adjusted
- `Address` details new data structure
- `Block` details new data structure
- `Addresses` and `Blocks` interfaces
- `urls` and `routes` names
> Addresses Blocks API data adjustment

- src/components/Progress/LinearProgress/LinearProgress.styles.ts
- src/components/Progress/LinearProgress/LinearProgress.tsx
- src/pages/Blocks/Blocks.tsx
- src/pages/Richlist/Richlist.helpers.tsx
- src/pages/Richlist/Richlist.tsx
- src/utils/constants/urls.ts
- src/utils/types/IRank.ts
- src/utils/types/IRichlists.ts
Added
- `LinearProgress` component with styles
- `Richlist` page
- `Current Balance` table
- `Wealth Distribution` table
- `Richlist` url and interface
Removed
- `Blocks` table name
> Richlist page

- src/components/Header/Header.tsx
- src/components/Progress/LinearProgress/LinearProgress.styles.ts
- src/components/Progress/LinearProgress/LinearProgress.tsx
- src/components/Summary/Summary.styles.ts
- src/components/Summary/Summary.tsx
- src/layouts/Dashboard/Dashboard.tsx
- src/pages/Network/Network.tsx
- src/utils/constants/urls.ts
- src/utils/types/IConnections.ts
Moved
- `Summary` below search bar
Adjusted
- `Linear progress` styles
- `Network` page to display new API data
Removed
- `CONNECTIONS` url
- `Connections` interface
> Network page adjustment

- src/components/Footer/Footer.styles.ts
- src/components/Footer/Footer.tsx
- src/components/Sidebar/SideBar.helpers.tsx
- src/components/Sidebar/Sidebar.styles.ts
- src/components/Sidebar/Sidebar.tsx
- src/utils/constants/urls.ts
Added
- `Telegram` and `GitHub` icons
Updated
- `Sidebar` footer icons
- `App` footer position and height to match sidebar footer height
> Footer icons size and position

- src/components/Map/Map.options.ts
- src/components/Map/Map.tsx
- src/pages/Explorer/Explorer.tsx
- src/pages/Network/Network.tsx
- src/theme/variants.ts
- src/utils/types/INetwork.ts
Added
- `Network` structure and interface
- `Map` peers and masternodes
> Network new API data and map adjustment 

- src/components/Charts/DoughnutChart/DoughnutChart.tsx
- src/components/Footer/Footer.styles.ts
- src/components/Footer/Footer.tsx
- src/components/Sidebar/Sidebar.styles.ts
- src/components/Sidebar/Sidebar.tsx
- src/components/Table/Table.tsx
- src/pages/Explorer/Explorer.tsx
- src/pages/Explorer/SupernodeStatistics/SupernodeStatistics.helpers.ts
- src/pages/Explorer/SupernodeStatistics/SupernodeStatistics.tsx
Added
- `Supernode Statistics` chart and table
- `Footer` with smaller height
> Supernode Statistics & Footer adjustment

- src/components/Map/Map.options.ts
- src/components/Map/Map.tsx
- src/components/Map/map.css
- src/components/Sidebar/Sidebar.styles.ts
- src/pages/Explorer/Explorer.helpers.tsx
- src/pages/Explorer/Explorer.tsx
- src/theme/variants.ts
Added
- `Map` markers new data - PastelID, IP.
> Map Markers new data

- .circleci/config.yml
- add circleci scripts for CI/CD
> config: add cicd with circleci scripts

- src/App.tsx
- src/components/Charts/DoughnutChart/DoughnutChart.styles.ts
- src/components/InfoDrawer/InfoDrawer.tsx
- src/components/Map/Map.options.ts
- src/components/Map/Map.styles.ts
- src/components/Map/Map.tsx
- src/pages/Explorer/Explorer.helpers.tsx
- src/pages/Explorer/Explorer.tsx
- src/pages/Explorer/ExplorerMap/ExplorerMap.helpers.tsx
- src/pages/Explorer/ExplorerMap/ExplorerMap.options.ts
- src/pages/Explorer/ExplorerMap/ExplorerMap.styles.ts
- src/pages/Explorer/ExplorerMap/ExplorerMap.tsx
- src/pages/Explorer/SupernodeStatistics/SupernodeStatistics.tsx
- src/redux/actions/actionTypes.ts
- src/redux/actions/infoDrawerActions.ts
- src/redux/reducers/index.ts
- src/redux/reducers/infoDrawerReducer.ts
- src/theme/variants.ts
Added
- `InfoDrawer` component to display any kind of additional information
- `Explorer map` supernode and peer legend with quantity
Adjusted
- `Doughnut Chart` height
- `Explorer map` height, `peers` color, marker content and colors
> Explorer Map Upgrade

- src/components/Header/Header.styles.ts
- src/components/Header/Header.tsx
- src/components/InfinityTable/InfinityTable.styles.ts
- src/components/InfinityTable/InfinityTable.tsx
- src/components/SearchBar/SearchBar.tsx
- src/components/Summary/Summary.styles.ts
- src/components/Summary/Summary.tsx
- src/layouts/Dashboard/Dashboard.styles.ts
- src/pages/Explorer/Explorer.helpers.tsx
- src/pages/Explorer/Explorer.tsx
- src/pages/Explorer/ExplorerMap/ExplorerMap.options.ts
- src/pages/Explorer/ExplorerMap/ExplorerMap.tsx
- src/pages/Explorer/SupernodeStatistics/SupernodeStatistics.helpers.ts
- src/pages/Explorer/SupernodeStatistics/SupernodeStatistics.tsx
- src/pages/Supernodes/Supernodes.helpers.tsx
- src/theme/variants.ts
- src/utils/types/INetwork.ts
- Reduced height of search component input
- Reduce height of summary boxes
- Reduced gap between page title and summary component
- Changed all labels from "Masternodes" to "Supernodes"
- Color changed for "even" rows in tables
- Added hover effect when user will hover on some table row
> Design Update

- src/components/Summary/Summary.helpers.ts
- src/components/Summary/Summary.styles.ts
- src/components/Summary/Summary.tsx
- src/utils/types/ISummary.ts
Added
- `Summary` accounts block
- `Summary` average transactions per second block
Updated
- `Summary` interface
- `Summary` styles
> Summary blocks update

- src/pages/Explorer/LatestTransactions/LatestTransactions.helpers.tsx
- src/pages/Explorer/LatestTransactions/LatestTransactions.styles.ts
Added
- `Tooltip` in `Transaction` table on `Amount` column
> Transaction Amount Tooltip

- src/pages/Details/TransactionDetails/TransactionDetails.helpers.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.styles.ts
- src/pages/Details/TransactionDetails/TransactionDetails.tsx
- src/utils/types/ITransactions.ts
Added
- `Non Standard Transaction` info alert and styles
> Non Standard Transaction Info

- src/components/InfinityTable/InfinityTable.styles.ts
- src/components/InfinityTable/InfinityTable.tsx
- src/components/SearchBar/SearchBar.styles.ts
- src/components/SearchBar/SearchBar.tsx
- src/components/Summary/Summary.helpers.ts
- src/layouts/Dashboard/Dashboard.styles.ts
- src/pages/Blocks/Blocks.columns.ts
- src/pages/Blocks/Blocks.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.helpers.tsx
- src/pages/Explorer/LatestTransactions/LatestTransactions.columns.ts
- src/pages/Explorer/LatestTransactions/LatestTransactions.tsx
- src/pages/Movement/Movement.tsx
- src/pages/Supernodes/Supernodes.tsx
- src/routes/Routes.tsx
- src/utils/helpers/scrollToTop/scrollToTop.ts
Fixes for mobile views, change seo meta description, change summary box label, increase height of infinity tables
> Fixes for mobile views

- src/pages/Statistics/Statistics.tsx
- src/routes/index.tsx
- src/utils/constants/routes.ts
> Statistics Page

- src/pages/Details/TransactionDetails/TransactionDetails.helpers.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.tsx
- src/utils/types/ITransactions.ts
Adjusted
- `Transaction` confirmations from block
> Transaction Confirmations

- src/components/Charts/LineChart/LineChart.options.ts
- src/components/Charts/LineChart/LineChart.styles.ts
- src/components/Charts/LineChart/LineChart.tsx
- src/pages/Statistics/HashrateChart/HashrateChart.options.ts
- src/pages/Statistics/HashrateChart/HashrateChart.styles.ts
- src/pages/Statistics/HashrateChart/HashrateChart.tsx
- src/pages/Statistics/Statistics.tsx
- src/pages/Statistics/VolumeTransactionsChart/VolumeTransactionsChart.helpers.ts
- src/pages/Statistics/VolumeTransactionsChart/VolumeTransactionsChart.styles.ts
- src/pages/Statistics/VolumeTransactionsChart/VolumeTransactionsChart.tsx
- src/theme/variants.ts
- src/utils/constants/urls.ts
- src/utils/helpers/date/date.ts
- yarn.lock
Added
- `Statistics` Volume of Transactions chart
> Statistics Volume of Transactions Chart

- src/components/Charts/LineChart/LineChart.styles.ts
- src/components/Charts/LineChart/LineChart.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.tsx
- src/pages/Details/TransactionDetails/TransactionRawData.tsx
- src/pages/Statistics/HashrateChart/HashrateChart.helpers.ts
- src/pages/Statistics/HashrateChart/HashrateChart.tsx
- src/pages/Statistics/Statistics.helpers.tsx
- src/pages/Statistics/Statistics.styles.ts
- src/pages/Statistics/VolumeTransactionsChart/VolumeTransactionsChart.helpers.ts
- src/pages/Statistics/VolumeTransactionsChart/VolumeTransactionsChart.styles.ts
- src/pages/Statistics/VolumeTransactionsChart/VolumeTransactionsChart.tsx
Adjusted
- `Statistics` loading indicators on both charts
- `Transaction` toggle typo
Added
- `Statistics` charts zoom buttons
> Statistics charts upgrade

- src/pages/Details/BlockDetails/BlockDetails.styles.ts
- src/pages/Details/BlockDetails/BlockDetails.tsx
Added
- `Block details` header navigation
> Block Details header navigation

- src/pages/Statistics/HashrateChart/HashrateChart.options.ts
- src/pages/Statistics/VolumeTransactionsChart/VolumeTransactionsChart.helpers.ts
Updated
- `Statistics` charts visibility by increasing charts dots
> Charts visibility

- src/pages/Statistics/HashrateChart/HashrateChart.tsx
- src/pages/Statistics/Statistics.helpers.tsx
- src/pages/Statistics/Statistics.styles.ts
- src/pages/Statistics/VolumeTransactionsChart/VolumeTransactionsChart.tsx
Fixed
- `Statistics` charts zoom options
> Statistics Zoom Options fix

- src/pages/Blocks/BlockVisualization/BlockVisualization.styles.ts
- src/pages/Blocks/BlockVisualization/BlockVisualization.tsx
- src/pages/Blocks/Blocks.helpers.tsx
- src/pages/Blocks/Blocks.styles.ts
- src/pages/Blocks/Blocks.tsx
Added
- `Visual Blocks` into `Block` page above table
> Visual Blocks

- src/components/InfinityTable/InfinityTable.styles.ts
- src/components/Table/Table.styles.ts
- src/components/Table/Table.tsx
- src/pages/Movement/Movement.tsx
- src/pages/Supernodes/Supernodes.tsx
Improved
- `Movement` title and table name
- `Supernode` title and table name
- All tables headers to be bold
> Table improvement

- src/components/InfinityTable/InfinityTable.tsx
- src/pages/Supernodes/Supernodes.columns.ts
- src/pages/Supernodes/Supernodes.tsx
Added
- `Supernodes` table sorting by `Country` and `Last paid`
> Supernodes Sorting

- src/components/CopyButton/CopyButton.styles.ts
- src/components/CopyButton/CopyButton.tsx
- src/components/RouterLink/RouterLink.styles.ts
- src/components/RouterLink/RouterLink.tsx
- src/pages/Details/AddressDetails/AddressDetails.helpers.tsx
- src/pages/Details/BlockDetails/BlockDetails.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.helpers.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.tsx
- src/pages/Explorer/LatestTransactions/LatestTransactions.helpers.tsx
- src/pages/Movement/Movement.helpers.tsx
- src/pages/Richlist/Richlist.helpers.tsx
- src/pages/Supernodes/Supernodes.columns.ts
- src/pages/Supernodes/Supernodes.helpers.tsx
Added
- `Copy button` next to each `Address` and `TxId`
- `USD` price next for each address in transaction details
Adjusted
- Each `Address` and `TxId` text size
> Copy button + USD price + Visual adjustments

- src/components/Hourglass/Hourglass.styles.ts
- src/components/Hourglass/Hourglass.tsx
- src/components/InfinityTable/InfinityTable.tsx
- src/components/Progress/LinearProgress/LinearProgress.styles.ts
- src/components/Table/Table.styles.ts
- src/components/Table/Table.tsx
- src/pages/Explorer/LatestTransactions/LatestTransactions.helpers.tsx
- src/pages/Statistics/BlockStatistics/BlockStatistics.tsx
Updated
- `Hourglass` component
- `Table` and `InfinityTable` heights
- `Block Chart` y axis
> Hourglass, Table, Chart Visual Updates

- src/pages/Details/BlockDetails/BlockDetails.styles.ts
- src/pages/Details/TransactionDetails/TransactionDetails.helpers.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.tsx
- src/pages/Movement/Movement.columns.ts
- src/pages/Movement/Movement.helpers.tsx
Fixed
- `Block details` table
Added
- `Coinbase` info in `Transaction details`
- `Block height` with possibility of `Hourglass` in `Movement` table
> Final fixes

- .circleci/config.yml
This pull request adds staging deployment automation to circle ci pipeline.
> add staging deployment to ci

- .circleci/config.yml
* upgrade build image
* optimize cost by using 2cpu and 4G ram
> upgrade image version, optimize container tier

- src/utils/constants/statistics.ts
Update the preview images of the chart from backend.
> feat(view): charts  - update the preview images of chart

- src/components/InfinityTable/Filters.tsx
- src/components/InfinityTable/InfinityTable.styles.ts
- src/components/InfinityTable/InfinityTable.tsx
- src/components/Link/Link.styles.ts
- src/components/RouterLink/RouterLink.styles.ts
- src/components/SearchBar/SearchBar.styles.ts
- src/components/Summary/Summary.styles.ts
- src/pages/Blocks/Blocks.columns.ts
- src/pages/Blocks/Blocks.styles.ts
- src/pages/Blocks/Blocks.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.helpers.tsx
- src/pages/Details/TransactionDetails/TransactionDetails.styles.ts
- src/pages/Explorer/Explorer.styles.ts
- src/pages/Explorer/Explorer.tsx
- src/pages/Explorer/LatestBlocks.tsx
- src/pages/Explorer/LatestTransactions/LatestTransactions.columns.ts
- src/pages/Explorer/LatestTransactions/LatestTransactions.styles.ts
- src/pages/Explorer/LatestTransactions/LatestTransactions.tsx
- src/pages/Explorer/LatestTransactionsRT.tsx
- src/pages/Movement/Movement.columns.ts
- src/pages/Movement/Movement.styles.ts
- src/pages/Movement/Movement.tsx
- src/pages/Richlist/Richlist.styles.ts
- src/pages/Richlist/Richlist.tsx
- src/pages/Supernodes/Supernodes.columns.ts
- src/pages/Supernodes/Supernodes.styles.ts
- src/pages/Supernodes/Supernodes.tsx
- src/theme/index.ts
- Fixed UI issues for the explorer screen
- Updated the BLOCK_CONFIRMED_NUMBER >= 1
- updated color for links.
> implement for the ui and functionalites

- src/components/ChooseCluster/ChooseCluster.tsx
- src/utils/constants/statistics.ts
fixed images do not show in the historical statistics
> fixed images do not show in the historical statistics

- src/pages/Explorer/ExplorerMap/ExplorerMap.helpers.tsx
- src/pages/Explorer/ExplorerMap/ExplorerMap.styles.ts
- src/pages/Supernodes/Supernodes.tsx
- update tooltip for Supernode Statistics chart
- update UI for Supernode List
> Deploy Production 05/21/2024
